config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Devise-User
  devise_for :users

  resources :inicios
  resources :nosotros
  resources :novedades
  resources :cursos
  resources :exams, only: %i[index show]
  resources :blogs
  resources :contacts, only: %i[new create]

  # Auth
  authenticate :user do
    scope '/admin' do
      resources :nosotros, only: %i[new create edit update destroy]
      resources :cursos, only: %i[new create edit update destroy]
      resources :blog, only: %i[new create edit update destroy]
      resources :novedades, only: %i[new create edit update destroy]
      resources :exams, only: %i[new create edit update destroy]
    end
  end
  get '/google03f55790f1cbd5fe.html', to: redirect('google03f55790f1cbd5fe.html')

  root to: 'inicios#index'
  
end

app/models/blog.rb
class Blog < ApplicationRecord
  self.table_name = 'blogs'

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :content, presence: true
  validates :autor, presence: true
  validates :fecha, presence: false
  validates :cover_filename, allow_blank: true, format: { with: %r{\.(gif|jpg|png)\Z}i, message: 'Must be a URL for GIF, JPG or PNG image.'}
  

  # validates :cover_filename, presence: true
  # validate :cover_size_validations

# Add FriendlyId to blogs
  extend FriendlyId
  friendly_id :title, use: :slugged


  attr_accessor :cover


  after_save :save_cover_image, if: :cover
  #after_validation :file_field :cover, :on => :create|update, :allow_blank => true, :allow_nil => true

  def save_cover_image
    filename = cover.original_filename
    folder = "public/blogs/#{id}/cover"

    FileUtils::mkdir_p folder
    f = File.open File.join(folder, filename), 'wb'
    f.write cover.read
    f.close

    self.cover = nil
    update cover_filename: filename
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :find_blog, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @blogs = Blog.all.map(&:cover_filename)
    @blogs = Blog.paginate(:page => params[:page], per_page: 5)
    # redirect_to root_path if @blogs.empty? # si no tiene blog me redirecciona root_path 
  end

  def show; end

  def new
    @blog = Blog.new
  end

  def edit; end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfylly created!'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blog_url, notice: 'Blog was successfully destroyed!'
  end

  private

  def find_blog
    @blog = Blog.friendly.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :cover, :autor, :fecha)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :contenido %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :Upload_Imagen, class:'control-group' %>
    <%= f.file_field :cover ,class:'btn btn-info' %>
    <%= f.label :Subir_imagenes_con_formato_jpg_jpeg_png %>
  </div>

  <div class="form-group">
    <%= f.label :autor %>
    <%= f.text_field :autor, class: 'btn btn-default' %>
  </div>

  <div class="form-group">
    <%= f.label :fecha %>
    <%= f.datetime_select :fecha, class: 'btn btn-success' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
  <br>
    <h1>Editing Blog</h1>
    <%= render 'form', blog: @blog %> <br>

    <%= link_to 'Vista Previa', @blog, class:'btn btn-success'%>
    <%= link_to 'Regresar a Blog', blogs_path, class:'btn btn-info' %>

</div>
<br>

app/views/blogs/index.html.erb
<!--Start of blog-->
<section id="general">
        <% if user_signed_in? %>
            <div class="nav navbar-right">
                <%= link_to 'New Blog', new_blog_path, class: 'btn btn-primary' %>
            </div>
        <% end %><!--end user_signed-->
      <nav class="navbar navbar-default">
        <div class="row">
            <div class="col-md-12">
                <div class="latest_blog text-center"><br>
                    <div class="titulo-h2">CITUS School of English blog</div>
                    <br>
                    <br>
                   
                </div>
            </div>
        </div><!--end row-->
      </nav>
     
      <div class="container">
        <div class="row"><br>
                <% @blogs.each do |blog| %>
                <div class="col-xs-6 col-md-4">
                  <div class="img-responsive">
                    <div class="img-resize-post">
                      <img src="/blogs/<%= blog.id %>/cover/<%= blog.cover_filename %>" />

                    </div>
                  </div>
                </div>

                  <div class="col-xs-12 col-md-8">
                    <div class="header_blog_h1"><%= link_to blog.title, blog %></div><br>
                    <p><%= blog.fecha %> | By <%= blog.autor %></p>
                    <div class="blog_content"><%= truncate blog.content, :length => 350  %></div><br>
                    <div class="btn-group">
                    <%= link_to 'Leer mas...', blog, class: 'btn btn-info background-position'%></div><br>
                    <hr>
                  </div>

                    <% if user_signed_in? %>
                     <div class="form-group"> <br>
                       <%= link_to 'New Blog', new_blog_path, class:'btn btn-primary' %>
                       <%= link_to 'Show', blog, class: 'btn btn-info' %>
                       <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-success' %>
                       <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                    </div>
                  <% end %>
                <% end %>
            </div>
            <br>
            <ul class="pager">
              <%= will_paginate @blogs, renderer: BootstrapPagination::Rails %>
            </ul>
        </div><!--end row-->


    </div><!--End of container-->
</section><!--End section-->
<!--End of blog-->

<style media="screen">
.navbar-default {
background-color: #ff0000;
border-color: #0069ff;
}
.navbar-default .navbar-brand {
color: #ffffff;
}
.navbar-default .navbar-brand:hover,
.navbar-default .navbar-brand:focus {
color: #ffffff;
}
.navbar-default .navbar-text {
color: #ffffff;
}
.navbar-default .navbar-nav > li > a {
color: #ffffff;
}
.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
color: #ffffff;
}
.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:hover,
.navbar-default .navbar-nav > .active > a:focus {
color: #ffffff;
background-color: #0069ff;
}
.navbar-default .navbar-nav > .open > a,
.navbar-default .navbar-nav > .open > a:hover,
.navbar-default .navbar-nav > .open > a:focus {
color: #ffffff;
background-color: #0069ff;
}
.navbar-default .navbar-toggle {
border-color: #0069ff;
}
.navbar-default .navbar-toggle:hover,
.navbar-default .navbar-toggle:focus {
background-color: #0069ff;
}
.navbar-default .navbar-toggle .icon-bar {
background-color: #ffffff;
}
.navbar-default .navbar-collapse,
.navbar-default .navbar-form {
border-color: #ffffff;
}
.navbar-default .navbar-link {
color: #ffffff;
}
.navbar-default .navbar-link:hover {
color: #ffffff;
}

@media (max-width: 767px) {
.navbar-default .navbar-nav .open .dropdown-menu > li > a {
  color: #ffffff;
}
.navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,
.navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
  color: #ffffff;
}
.navbar-default .navbar-nav .open .dropdown-menu > .active > a,
.navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
.navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
  color: #ffffff;
  background-color: #0069ff;
  }
}
</style>

app/views/blogs/new.html.erb
<div class="container">
    <br>
    <h1>Nuevo Blog</h1>

      <%= render 'form', blog: @blog %> <br>
      <%= link_to 'Regresar a Blog', blogs_path, class: 'btn btn-primary' %>

  </div>
<br>

app/views/blogs/show.html.erb
<section id="general">
  <nav class="navbar navbar-default">
    <div class="row">
        <div class="col-md-12">
            <div class="latest_blog text-center"><br>
                <div class="titulo-h2"><%= @blog.title %></div>
                <div class="titulo-p"><%= @blog.fecha %> | By <%= @blog.autor %></div>
                <br>
                <br>
                <!-- <p></p> -->
                <!--<p>Novedades importantes de todo el trabajo que hacemos en nuestro Instituto y el porque la gente nos elige</p>-->

            </div>
        </div>
    </div><!--end row-->
  </nav>

  <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="latest_blog text-center">
              <br>
              <%= image_tag "/blogs/#{@blog.id}/cover/#{@blog.cover_filename}" if @blog.cover_filename? %>
              <br><br>
              <p><%= @blog.content %></p>
             <%# image_tag @blog.cover.url  if @blog.cover?%>
            <br>
            <br>
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_blog_path(@blog), class: 'btn btn-success' %>
            <% end %>
            <%= link_to 'Regresar a Citus Blog', blogs_path, class: 'btn btn-primary' %>
            <br>
          </div><!-- end latest_blog text-center  -->
        </div><!--End col-md-12-->
      </div><!--End row-->
  </div><!--End Container-->
</section>
<hr>

<br>
<style media="screen">
.navbar-default {
background-color: #ff0000;
border-color: #0069ff;
}
.navbar-default .navbar-brand {
color: #ffffff;
}
.navbar-default .navbar-brand:hover,
.navbar-default .navbar-brand:focus {
color: #ffffff;
}
.navbar-default .navbar-text {
color: #ffffff;
}
.navbar-default .navbar-nav > li > a {
color: #ffffff;
}
.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
color: #ffffff;
}
.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:hover,
.navbar-default .navbar-nav > .active > a:focus {
color: #ffffff;
background-color: #0069ff;
}
.navbar-default .navbar-nav > .open > a,
.navbar-default .navbar-nav > .open > a:hover,
.navbar-default .navbar-nav > .open > a:focus {
color: #ffffff;
background-color: #0069ff;
}
.navbar-default .navbar-toggle {
border-color: #0069ff;
}
.navbar-default .navbar-toggle:hover,
.navbar-default .navbar-toggle:focus {
background-color: #0069ff;
}
.navbar-default .navbar-toggle .icon-bar {
background-color: #ffffff;
}
.navbar-default .navbar-collapse,
.navbar-default .navbar-form {
border-color: #ffffff;
}
.navbar-default .navbar-link {
color: #ffffff;
}
.navbar-default .navbar-link:hover {
color: #ffffff;
}

@media (max-width: 767px) {
.navbar-default .navbar-nav .open .dropdown-menu > li > a {
  color: #ffffff;
}
.navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,
.navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
  color: #ffffff;
}
.navbar-default .navbar-nav .open .dropdown-menu > .active > a,
.navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
.navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
  color: #ffffff;
  background-color: #0069ff;
}
}
</style>
<br>