config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Devise-User
  devise_for :users

  resources :inicios
  resources :nosotros
  resources :novedades
  resources :cursos
  resources :exams, only: %i[index show]
  resources :blogs
  resources :contacts, only: %i[new create]

  # Auth
  authenticate :user do
    scope '/admin' do
      resources :nosotros, only: %i[new create edit update destroy]
      resources :cursos, only: %i[new create edit update destroy]
      resources :blog, only: %i[new create edit update destroy]
      resources :novedades, only: %i[new create edit update destroy]
      resources :exams, only: %i[new create edit update destroy]
    end
  end
  get '/google03f55790f1cbd5fe.html', to: redirect('google03f55790f1cbd5fe.html')

  root to: 'inicios#index'
  
end

app/models/nosotro.rb
class Nosotro < ApplicationRecord
  self.table_name = 'nosotros'

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :content, presence: true
  validates :cover_filename, allow_blank: true, format: { 
    with: %r{\.(jpeg|jpg|png)\Z}i, 
    message: 'Must be a URL for GIF, JPG or PNG image.'
  }


  # Add FriendlyId to Nosotros
  extend FriendlyId
  friendly_id :title, use: :slugged

  attr_accessor :cover

  after_save :save_cover_image, if: :cover

  def save_cover_image
    filename = cover.original_filename
    folder = "public/nosotros/#{id}/cover"

    FileUtils::mkdir_p folder
    f = File.open File.join(folder, filename), 'wb'
    f.write cover.read
    f.close

    self.cover = nil
    update cover_filename: filename
  end
end

app/controllers/nosotros_controller.rb
class NosotrosController < ApplicationController
  before_action :find_nosotros, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @nosotros = Nosotro.all
  end

  def show
  end

  def new
    @nosotro = Nosotro.new
  end

  def edit; end

  def create
    @nosotro = Nosotro.new(nosotro_params)

    if @nosotro.save
      redirect_to @nosotro, notice: 'Nosotros was successfully created!'
    else
      render :new
    end
  end

  def update
    if @nosotro.update(nosotro_params)
      redirect_to @nosotro, notice: 'Nosotros was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @nosotro.destroy
    redirect_to nosotros_url, notice: 'Nosotros was successfully destroyed!'
  end

  private

  def find_nosotros
    @nosotro = Nosotro.friendly.find(params[:id])
  end

  def nosotro_params
    params.require(:nosotro).permit(:title, :content, :cover)
  end
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/views/nosotros/_form.html.erb
<%= form_with(model: nosotro, local: true) do |f| %>
  <% if nosotro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nosotro.errors.count, "error") %> prohibited this nosotros from being saved:</h2>

      <ul>
      <% nosotro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :titutlo %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :contenido %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :Upload_Image, class:'control-group' %>
    <%= f.file_field :cover, class: 'btn btn-info' %>
    <%= f.label :Subir_imagenes_con_formato_jpg_jpeg_png %>
  </div>


  <div class='actions'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/nosotros/edit.html.erb
<div class="container">
  <br>
    <h2>Editing Nosotros</h2>

    <%= render 'form', nosotro: @nosotro %><br>

    <%= link_to 'Show', @nosotro , class:'btn btn-success'%>
    <%= link_to 'Regesar a Nosotros', nosotros_path , class: 'btn btn-primary'%>
</div>
<br>

<style>
  #footer {
    margin-top: 10.75%;
  }
</style>

app/views/nosotros/index.html.erb
<!--Start of conocenos-->
    <section id="cursos">
        <div class="cursos_overlay">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="cursos_header text-center">
                            <h2>Estudi&aacute;</h2>
                            <p>Citus School of English se destaca por su metodología de enseñanza, basada en la conversación, como modalidad esencial para lograr el aprendizaje natural del idioma..</p>
                        </div>
                    </div>
                </div>
                <!--End of row-->
                <section id="carousel">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="carousel slide" id="fade-quote-carousel" data-ride="carousel" data-interval="5000">
                                    <!-- Carousel indicators -->
                                    <ol class="carousel-indicators">
                                        <li data-target="#fade-quote-carousel" data-slide-to="0" class="active"></li>
                                        <li data-target="#fade-quote-carousel" data-slide-to="1"></li>
                                    </ol>
                                    <!-- Carousel items -->
                                    <div class="carousel-inner">
                                        <div class="active item">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <!-- <div class="img-thumbnail">
                                                      <%= image_tag('ingles1.jpg', :alt => 'ingles1') %>
                                                    </div><br><br> -->
                                                    <div class="cursos_content">
                                                      <h2>Hoy en día, en un mundo cada vez más globalizado y sobre todo conectado, el Inglés se ha convertido en algo imprescindible.</h2>
                                                    </div>

                                                </div>
                                                <div class="col-md-6">
                                                    <div class="img-thumbnail">
                                                      <%= image_tag('ingles2.jpg', :alt => 'ingles2') %>
                                                    </div><br>
                                                    <!-- <div class="cursos_content">
                                                      <h1>Hoy en día, en un mundo cada vez más globalizado y sobre todo conectado, el Inglés se ha convertido en algo imprescindible.</h1>
                                                    </div> -->
                                                </div>
                                            </div>
                                        </div>
                                        <!--End of item with active-->
                                        <div class="item">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="img-thumbnail">
                                                      <%= image_tag('ingles3.jpg', :alt => 'ingles3') %>
                                                    </div><br>
                                                    <!-- <div class="cursos_content">
                                                      <h1>Hoy en día, en un mundo cada vez más globalizado y sobre todo conectado, el Inglés se ha convertido en algo imprescindible.</h1>
                                                    </div> -->

                                                </div>
                                                <div class="col-md-6">
                                                    <!-- <div class="img-thumbnail">
                                                      <%= image_tag('ingles4.jpg', :alt => 'ingles4') %>
                                                    </div><br> -->
                                                    <div class="cursos_content">
                                                      <h1>Hoy en día, en un mundo cada vez más globalizado y sobre todo conectado, el Inglés se ha convertido en algo imprescindible.</h1>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <!--End of item-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--End of row-->
                    </div>
                    <!--End of container-->
                </section>
                <!--End of carousel-->
            </div>

        </div>
        <!--End of container-->
    </section>
    <!--end of nosotros-->

<!-- Start of nosotros section -->
    <br>
    <div class="container">
        <% if user_signed_in? %>
        <div class="nav navbar-right">
                <h2>Nuevo Nosotros!</h2>
         <%= link_to 'New Nosotros', new_nosotro_path, class: 'btn btn-primary' %>
       </div>
       <% end %>
       <br>
           <% @nosotros.each do |nosotro| %>
              <h2><%= link_to nosotro.title, nosotro %></h2>
               <p><%= truncate nosotro.content, :length => 450  %></p><br>
               <%= link_to 'Leer mas...', nosotro, class: 'btn btn-info'%>
                <br><br>
               <% if user_signed_in? %>
               <div class="form-group">
                 <% link_to 'Show', nosotro, class: 'btn btn-info' %>
                 <% link_to 'Edit', edit_nosotro_path(nosotro), class:'btn btn-success' %>
                 <% link_to 'Destroy', nosotro, method: :delete, data: {confirm: 'Are you sure?'}, class:'btn btn-danger' %>
                 <% end %>
              <% end %>
              </div>
    </div><!-- end container  -->

    <!--Start of volunteer-->
    <section id="volunteer">
        <div class="container">
            <div class="row vol_area">
                <div class="col-md-8">
                    <div class="volunteer_content">
                        <h3>Estudi&aacute; con <span>nosotros</span></h3>
                        <p>Ingl&eacute;s con nosotros es muy f&aacute;cil , poseemos un sistema rapido y efectivo ENTERATE! </p>
                        <p>EX&Aacute;MENES DE LA UNIVERSIDAD DE CAMBRIDGE Y OTROS</p>
                        <p>Conoc&eacute; todo sobre los Ex&aacute;menes INTERNACIONALES de ingl&eacute;s del Trinity College of London</p>
                        <p>Conoc&eacute; todo sobre los EX&Aacute;MENES INTERNACIONALES de ingl&eacute;s del Trinity College of London</p>
                        <p>ES HORA DE ALCANZAR TUS OBJETIVOS..!!!</p>
                    </div>
                </div>
                <!--End of col-md-8-->
                <div class="col-md-3 col-md-offset-1">
                    <div class="join_us">
                        <%= link_to 'Enterate ', novedades_index_path(@novedades), class:'vol_cust_btn' %><br><br><br>
                        <%= link_to 'Exámenes', exams_path(@examens), class:'vol_cust_btn' %>

                      </div>
                </div>
                <!--End of col-md-3-->
            </div>
            <!--End of row and vol_area-->
        </div>
        <!--End of container-->
    </section>
    <!--end of volunteer-->
    <br>

app/views/nosotros/new.html.erb
<div class="container">
    <br>
    <h2>Nosotros</h2>
      <%= render 'form', nosotro: @nosotro %> <br>
      <%= link_to 'Back', nosotros_path, class: 'btn btn-primary'%>
</div>
<br>

app/views/nosotros/show.html.erb
<section id="general">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="latest_blog text-center">
          <h2><%= @nosotro.title %></h2><br>
          <%= image_tag "/nosotros/#{@nosotro.id}/cover/#{@nosotro.cover_filename}" if @nosotro.cover_filename? %><br><br>
          <p><%= @nosotro.content %></p><br>

    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_nosotro_path(@nosotro), class: 'btn btn-success' %>
    <% end %>

      <%= link_to 'Regresar a Conocenos', nosotros_path , class: 'btn btn-primary'%>
    </div><!-- End row-->
  </div><!--End container-->
</section>
<br>


<style>
  #footer {
    margin-top: 12.90%;
  }
</style>