config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Devise-User
  devise_for :users

  resources :inicios
  resources :nosotros
  resources :novedades
  resources :cursos
  resources :exams, only: %i[index show]
  resources :blogs
  resources :contacts, only: %i[new create]

  # Auth
  authenticate :user do
    scope '/admin' do
      resources :nosotros, only: %i[new create edit update destroy]
      resources :cursos, only: %i[new create edit update destroy]
      resources :blog, only: %i[new create edit update destroy]
      resources :novedades, only: %i[new create edit update destroy]
      resources :exams, only: %i[new create edit update destroy]
    end
  end
  get '/google03f55790f1cbd5fe.html', to: redirect('google03f55790f1cbd5fe.html')

  root to: 'inicios#index'
  
end

app/models/exam.rb
class Exam < ApplicationRecord
  self.table_name = 'exams'
  
  validates :title, presence: true, length: { minimum: 5 }
  validates :title, uniqueness: true

  validates :cover_filename, allow_blank: true, format: { with: %r{\.(gif|jpg|png)\Z}i, message: 'Must be a URL for GIF, JPG or PNG image.'}

# Add FriendlyId to Examenes
  #extend FriendlyId
  #friendly_id :title, use: :slugged

  # validates :cover_filename, presence: true
  # validate :cover_size_validations
  attr_accessor :cover

  after_save :save_cover_image, if: :cover

  def save_cover_image
    filename = cover.original_filename
    folder = "public/examenes/#{id}/cover"

    FileUtils::mkdir_p folder
    f = File.open File.join(folder, filename), 'wb'

    f.write cover.read
    f.close

    self.cover = nil
    update cover_filename: filename
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :find_examen, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @exams = Exam.all
  end

  def show; end

  def new
    @exam = Exam.new
  end

  def edit; end

  def create
    @exam = Exam.new(examen_params)

    if @exam.save
      redirect_to @exam, notice: 'Examen was successfully created!'
    else
      render :new
    end
  end

  def update
    if @exam.update(examen_params)
      redirect_to @exam, notice: 'Examen wassuccessfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @exam.destroy
    redirect_to exams_url, notice: 'Examen was successfully destroyed!'
  end

  private
  
  def find_examen
    @exam = Exam.find(params[:id])
  end

  def examen_params
    params.require(:exam).permit(:title, :content, :cover)
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true)  do |f| %>

  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this Examen from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :contenido %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :Upload_Imagen, class:'control-group' %>
    <%= f.file_field :cover, class:'btn btn-info' %>
    <%= f.label :Subir_imagenes_con_formato_jpg_jpeg_png %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<div class="container">
  <br>
    <h1>Editing Examenes</h1>

    <%= render 'form', exam: @exam %><br>

    <%= link_to 'Vista Previa', @exam, class:'btn btn-success' %>
    <%= link_to 'Regresar a Examenes', exams_path, class: 'btn btn-primary' %>

</div>
<br>

<style>
  #footer {
    margin-top: 10.75%;
  }
</style>

app/views/exams/index.html.erb
<!--Start of blog-->
<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="latest_blog text-center">
                  <div class="titulo-h1">
                     EXÁMENES
                  </div>
                    <div class="content-p">En CITUS School of English preparamos a nuestros alumnos para rendir los exámenes internacionales de la Universidad de CAMBRIDGE,
                  TOEFL y TRINITY que son indicadores reconocidos mundialmente como nivel superior de inglés aprendido.</div>
                </div>
            </div>
        </div>
        <!--End of row-->
        
        <% @exams.each_with_index do |exam, index| %>
            <% if index % 3 == 0 %>
                <div class="row" style='margin-top: 20px;'>
            <% end %>

            <div class="col-md-4">
                <div class="blog_news">
                    <div class="single_blog_item">
                         <div class="blog_img">
                         <%# image_tag("trinity#{index+1}.jpg", :alt => 'photo', :height=> "300" , :width =>"300") %>
                         <img src="/examenes/<%= exam.id %>/cover/<%= exam.cover_filename %>" /> 
                        </div> 
                        <div class="blog_content">
                          <div class="examenes_header-h2">
                            <%= link_to truncate(exam.title, :length => 36), exam %>
                          </div>
                            <div class="expert">
                                <p class="content-p"><%= truncate exam.content, :length => 133 %></p>
                            </div>
                            <% if user_signed_in? %>
                                <div class="form-group">
                                <br>
                                <%= link_to 'Show', exam, class: 'btn btn-info' %>
                                <%= link_to 'Edit', edit_exam_path(exam), class: 'btn btn-success' %>
                                <%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

            <% if index % 3 == 2 %>
                </div>
            <% end %>
        <% end %>

        </div>
        <!--End of row-->
    </div>
    <!--End of container-->
</section>
<!-- end of blog-->
<div class="container">
<% if user_signed_in? %>
<div class='nav navbar-right'>
  <%= link_to 'New Examen', new_exam_path, class: 'btn btn-primary' %>
</div>
<% end %>
</div>

app/views/exams/new.html.erb
<div class="container">
    <br>
    <h1>Examenes Internacionales </h1>

    <%= render 'form', exam: @exam %> <br>
    <%= link_to 'Regresar a Examenes', exams_path, class: 'btn btn-primary' %>

</div>
<br>

app/views/exams/show.html.erb
<section id="blog">
  <div class="container">
    <div class="row">
      <divl class="col-md-12">
        <div class="latest_blog text-center">

          <div class="titulo-h1">
            <%= @exam.title %>
          </div>
          <div class="content-p">
            <%= @exam.content %>
          </div>
            <br>
            <%# image_tag "/examenes/#{@exam.id}/cover/#{@exam.cover_filename}" if @exam.cover_filename? %>
            <%= image_tag "/examenes/#{@exam.id}/cover/#{@exam.cover_filename}" if @exam.cover_filename? %><br>
            <br>

            <br>
            <br>
            <% if user_signed_in? %>
            <%= link_to 'Edit', edit_exam_path(@exam), class: 'btn btn-success' %>
            <% end %>
            <%= link_to 'Regresar a Examenes', exams_path, class: 'btn btn-primary' %>
          <br>
          <br>
        </div><!--end novedad_header -->
      </div> <!--end col-md-12-->
    </div>  <!-- end row -->
  </div><!--end container-->
</section><!-- end section -->
<br>

</div>
<br>