config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Devise-User
  devise_for :users

  resources :inicios
  resources :nosotros
  resources :novedades
  resources :cursos
  resources :exams, only: %i[index show]
  resources :blogs
  resources :contacts, only: %i[new create]

  # Auth
  authenticate :user do
    scope '/admin' do
      resources :nosotros, only: %i[new create edit update destroy]
      resources :cursos, only: %i[new create edit update destroy]
      resources :blog, only: %i[new create edit update destroy]
      resources :novedades, only: %i[new create edit update destroy]
      resources :exams, only: %i[new create edit update destroy]
    end
  end
  get '/google03f55790f1cbd5fe.html', to: redirect('google03f55790f1cbd5fe.html')

  root to: 'inicios#index'
  
end

app/views/layouts/_footer.html.erb
<!--Start of footer-->
<section id="footer">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-8">
                <div class="copyright">
                 <p> Copyright &copy; <%= link_to 'CITUS School of English', 'http://citusweb.com.ar'%> 2000 - <span><%= Date.today.year %></span> &#8212; All Rigths Reserved</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="designer">
                    <h6>Created by <%= link_to 'TINIXTECH.COM', 'http://tinixtech.com' %></h6>
                </div>
            </div>
        </div>
        <!--End of row-->
    </div>
    <!--End of container-->
</section>
<!--End of footer-->
 

app/views/layouts/_header.html.erb
<div class="header_menu text-center" data-spy="affix" data-offset-top="50" id="nav">
  <div class="container">
    <nav class="navbar navbar-default zero_mp">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand custom_navbar-brand">
          <%# link_to (image_tag('logo.png', :alt => 'logo')), "http://citusweb.com.ar" %>
          <%= image_tag('logo.png', :alt => 'logo-Citus') %></a>
      </div>
      <!--End of navbar-header-->

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse zero_mp" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right main_menu">
          <li class="<%= active_action?(params, 'inicios') %>"><%= link_to 'Inicio', root_path %></li>
          <li class="<%= active_action?(params, 'nosotros') %>"><%= link_to 'Conocenos',nosotros_index_path %></li>
          <li class="<%= active_action?(params, 'cursos') %>"><%= link_to 'Cursos',cursos_index_path %></li>
          <li class="<%= active_action?(params, 'exams') %>"><%= link_to 'Examenes', exams_path %></li>
          <li class="<%= active_action?(params, 'novedades') %>"><%= link_to 'Novedades', novedades_index_path %></li>
          <li class="<%= active_action?(params, 'blogs') %>"><%= link_to 'Blog', blogs_path %></li>
          <li class="<%= active_action?(params, 'contacts') %>"><%= link_to 'Contacto', new_contact_path%></li>

          <% if user_signed_in? %>
            <!--<li><%# link_to 'Admin Panel', '/admin'%></li> -->
            <li><%= link_to('Cerrar Sesión',destroy_user_session_path, method: :delete) %></li>
          <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </nav>
    <!--End of nav-->
  </div>
  <!--End of container-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Citus School English | Tu lugar! </title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Architects+Daughter" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Galindo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Happy+Monkey" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Archivo+Black" rel="stylesheet">
    <meta name="google-site-verification" content="google03f55790f1cbd5fe"

    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--    Google Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head><!--Ended header -->


   <body data-spy="scroll" data-target="http://citusweb.com.ar">
<!-- start facebook -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- end facebook -->

      <!--Start Hedaer Section-->
      <section id="header">
          <div class="header-area">
              <div class="top_header">
                  <div class="container">
                      <div class="row">
                          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 zero_mp">
                              <div class="phone">
                                  <i class="glyphicon glyphicon-home"></i>
                                  <!-- <i class="fa fa-home floatleft"></i> -->
                                  <p>Luis Agote 2585, Los Naranjos,Córdoba Argentina</p>
                              </div>
                          </div>
                          <!--End of col-md-4-->
                          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 zero_mp">
                              <div class="phone">
                                <i class="glyphicon glyphicon-earphone"></i>
                                  <p>+ 54 0351 466-4378</p>
                              </div>
                          </div>
                          <!--End of col-md-4-->
                          <div class="col-md-4">
                              <div class="social_icon text-right">
                                <%= link_to 'https://www.facebook.com/citusweb/', target: :_blank do %>
                                  <%= image_tag('facebook.png',width: '20px' ,class: :facebook_icon, :alt => 'Facebook') %>
                                <% end %>

                                <%= link_to 'https://twitter.com/citusweb', target: :_blank do %>
                                 <%= image_tag('twitter.png', width: '20px', class: :twitter_icon, :alt => 'twitter') %>
                                 <% end %>

                                  <%= link_to 'https://youtube.com/citus', target: :_blank do %>
                                  <%= image_tag('youtube.png', width: '20px', class: :youtube_icon, :alt => 'youtube' ) %>
                                  <% end %>

                                <%= link_to 'https://instagram.com/citusweb/', target: :_blank do %>
                                <%= image_tag('instagram.png', width: '20px', class: :instagram_icon, :alt => 'instagram' ) %>
                                <% end %>

                              <!-- Begin-Auth -->
                                  <% if user_signed_in? %>
                                    <%= link_to(current_user.email, '/admin') %>
                                    <%= link_to(image_tag('cerrar.png', width: '20px'), destroy_user_session_path, method: :delete)%>
                                  <% else %>
                                    <%= link_to(image_tag('login.png',width: '20px'), '/users/sign_in')%>
                                  <% end %>
                                <!-- End-Auth -->

                              </div>
                          </div>
                          <!--End of col-md-4-->
                      </div>
                      <!--End of row-->
                  </div>
                  <!--End of container-->
              </div>
              <!--End of top header-->
              <%= render 'layouts/header' %>
              <!--End of header menu-->
          </div>
          <!--end of header area-->
      </section>
      <!--End of Header Section-->
    <br><br>
    <%= yield %>
  </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

<script>
  img {
      max - width: 100 %;
      height: auto;
      border - color: #000;
      border - radius: 1 %;
      margin - top: 10 %;
    }
</script>